---
tags:
  - Note_done
  - Informatique
source: UMons - Algorithme et programmation 1
---

Link :
_Python : Notions de base_
1. [[1.1.9 - Exception]]

_Python : Fonctions_
1. [[3.3.1 - Module (Python)]]

_Python : Récursivité_
1. [[5.2.1 - Fonction isinstance()]]

_Python : Tuple_
1. [[11.1.1 - Tuple (Python)]]

_Python : Fichiers et exceptions_
1. [[Python]]
2. [[12.2.1.1 - Méthode ‘strip’]]
3. [[12.2.3 - Méthode 'readlines']]
4. [[12.4.1 - Lancer une exception]]

**Introduction**
Jusqu’à présent, quand une exception se produit, le script s’interrompt brutalement. Comment gérer les exceptions pour éviter cette sortie brutale et plutôt effectuer du code spécifique à ce moment ?
# Comment gérer les exceptions ?
1. Solution 1 : utiliser des instructions conditionnelles pour éviter les exceptions
	1. _Inconvénients_ :
		1. code difficile à lire et à écrire car nombreux cas possibles ; 
		2. les tests peuvent être coûteux en temps de calcul ; 
		3. nécessite de penser aux cas exceptionnels, et de les gérer “a priori”, plutôt que de se concentrer sur le code principal ; 
		4. le nombre d’exceptions possibles peut-être très important. Par exemple, pour les fichiers, l’exception suivante suggère qu’il y a au moins 21 types d’erreurs possibles !
2. Solution 2 : Utiliser les instructions "`try`" et "`except`" qui permettent de gérer les problèmes qu'ils se produisent lors de l'exécution du programme

## Liste des erreurs d'exceptions
| Nom de l'exception | Signification du nom de l'exception                                     |
| ------------------ | ----------------------------------------------------------------------- |
| ValueError         | Erreur de valeur (i.e. ne respecte pas les pré-conditions)              |
| TypeError          | Erreur de type pour un paramètre                                        |
| IndexError         | Indice hors bornes                                                      |
| IOError            | Toutes les erreurs relatives aux fichiers (ou autres entrées / sorties) |

## Syntaxe
```python
try:
		# code principal
except:
		# Code spécifique en cas d'exception
```

### Quel est le comportement de ce code ?
1. Le code principal est exécuté. 
2. Dès que celui-ci produit une exception, il est interrompu et le code spécifique est exécuté. 
3. Si aucune exception ne s’est produite, le code spécifique n’est pas exécuté.

_Remarque_ :
1. On dit qu'on attrape (catch) une exception dans une clause `except`

#### Exemple
```python
try: 
		i = int(input('Entier : ')) 
		print('Nous pouvons travailler avec', i) 
except: 
		print('Je ne peux travailler qu\'avec un entier') 
print('Fin du programme')

"""
1) cas 1 : Entier : 2 
Nous pouvons travailler avec 2 
Fin du programme

2) cas 2 : Entier : hello 
Je ne peux travailler qu’avec un entier 
Fin du programme
"""
```

### Peut-on faire autre chose en utilisant les instructions "try" et "except" ?
On peut spécifier dans la clause "`except`" le type d'exception que l'on veut attraper

#### Exemple
```python
valid_int = False 

while not valid_int: 
	try: 
		x = int(input("Please enter a number: ")) 
		valid_int = True 
	except ValueError: 
		print("Oops! That was no valid integer. Try again...") 
print('Now I\'m sure that', x, 'is a valid integer.')
```

_Remarque_ :
1. Si une autre exception qu’une `ValueError` se produit, elle n’est pas rattrapée et le comportement sera celui habituel : le programme s’arrête brutalement.
2. On peut spécifier plusieurs clauses "`except`", pour gérer différents types d’exceptions.


#### Exemple de la remarque 2 : 
```python
try: 
	f = open('myfile.txt') 
	s = f.readline() 
	i = int(s.strip()) 
	print('All is OK with', i) 
except IOError: 
	print('Cannot open myfile.txt') 
except ValueError: 
	print('Could not convert', s.strip(), 'to an integer.') 
except: 
	print('Unexpected error.') 
	raise
```
_Remarque_ :
1. le dernier cas permet de relancer les exceptions qui n’ont pas été spécifiquement gérées
2. On peut spécifier un `tuple` d’exceptions à gérer dans une même clause "`except`"
3. On peut placer un "`else`", après les clauses "`except`". Il sera exécuté si aucune exception n’est produite. C’est utile dans le cas où il faut exécuter du code seulement si l’instruction "`try`" n’a pas provoqué d’exceptions.

#### Exemple de la remarque 2 et 3
```python
# Ex de la remarqur 2
try: 
	f = open('myfile.txt') 
	s = f.readline() 
	i = int(s.strip()) 
except (IOError, ValueError): 
	print('Cannot open file or cannot convert integer')


# Ex de la remarque 3
import sys 

for arg in sys.argv[1:]: 
	try: f = 
		open(arg, 'r') 
	except IOError: 
		print('cannot open', arg) 
	else: 
		print(arg, 'has', len(f.readlines()), 'lines') 
		f.close()
```